services:
  alpine-ttypd-hl:
    build: .
    image: hackinglab/alpine-ttyd-hl:3.2
    restart: always
    environment:
    - AUTHOR=e1
    - HL_USER_USERNAME=hacker
    - HL_USER_PASSWORD=compass
    - GOLDNUGGET=flag
    ports:
      - 7681:7681
    volumes:
      - /:/tmp


